### ISSUE TITLE
bbr issues

### ISSUE THREAD

**Issue by Azson** [Azson/DTP-emulator#10]
https://github.com/Azson/DTP-emulator/blob/5e76b1939a4deeab9c0f3675c1ce985c7bf5ac0f/player/examples/cmp_bbr.py#L29

why not use 1/bbr_high_gain?

**Comment by Azson** [comment]
或者说bbr_high_gain为什么还要+1

**Comment by bladelei** [comment]
> 或者说bbr_high_gain为什么还要+1
导过来也可以的，参数的设定好像涉及一些推导公式，我之前好像在哪看到，我去找找
